name: Build-extra CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - CONTRIBUTING.md
      - README
      - README.md
      - RELNOTES
      - SECURITY.md
      - 'etc/**'
      - 'src/firecfg/firecfg.config'
      - '.github/ISSUE_TEMPLATE/*'
      - '.github/pull_request_template.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - CONTRIBUTING.md
      - README
      - README.md
      - RELNOTES
      - SECURITY.md
      - 'etc/**'
      - 'src/firecfg/firecfg.config'
      - '.github/ISSUE_TEMPLATE/*'
      - '.github/pull_request_template.md'

jobs:
  build-clang:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
    - name: configure
      run: CC=clang-11 ./configure --enable-fatal-warnings
    - name: make
      run: make
  scan-build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
    - name: install clang-tools-11
      run: sudo apt-get install clang-tools-11
    - name: configure
      run: CC=clang-11 ./configure --enable-fatal-warnings
    - name: scan-build
      run: NO_EXTRA_CFLAGS="yes" scan-build-11 --status-bugs make
  cppcheck:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
    - name: install cppcheck
      run: sudo apt-get install cppcheck
    - name: cppcheck
      run: cppcheck -q --force --error-exitcode=1 --enable=warning,performance .
